version: "3.8"
name: graph-todo_pro
services:
  client:
    container_name: client
    image: santgt5/client-graphql-todo
    ports:
      - 5173:5173

  api:
    container_name: api
    restart: always
    image: santgt5/server-graphql-todo
    environment:
      - MONGODB_URL=$MONGODB_URL # MongoDB Access
    ports:
      - 4000:4000 # Apollo
