version: "3.8"
name: graph-todo_dev
services:
  client:
    stdin_open: true
    container_name: client_dev
    ports:
      - 5173:5173
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    volumes:
      - /app/node_modules
      # "./client" is where our Docker.dev is (folder name)
      # "./app" is our "WORKDIR"
      - ./client:/app

  api:
    container_name: api_dev
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 4000:4000
    depends_on:
      - mongo
      - mongo-express
    networks:
      - todo-app
    environment:
      MONGODB_URL: mongodb://mongo:27017/graphqlTodo_dev

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - todo-app
    volumes:
      - mongo-data:/data/db
    command: mongod --quiet --logpath /dev/null

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    networks:
      - todo-app

networks:
  todo-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
