version: "3.8"
name: graph-todo_pro
services:
  client:
    container_name: client
    image: santgt5/client-graphql-todo
    ports:
      - 5173:5173
  server:
    container_name: api
    image: santgt5/server-graphql-todo
    ports:
      - 4000:4000
