version: "3.8"
name: graph-todo_pro
services:
  client:
    container_name: client
    image: santgt5/client-graphql-todo

  api:
    container_name: api
    image: santgt5/server-graphql-todo
    environment:
      MONGODB_URL: mongodb://mongo:27017/graphqlTodo
