version: "3.8"
name: graph-todo
services:
  nginx:
    restart: always
    depends_on:
      - client
      - api
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 3050:80
    networks:
      - todo-app

  client:
    stdin_open: true
    container_name: client
    ports:
      - 5173:5173
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    volumes:
      - /app/node_modules
      - ./client:/app
    networks:
      - todo-app

  api:
    container_name: api
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 4000:4000
    depends_on:
      - mongo
      - mongo-express
    networks:
      - todo-app
    environment:
      MONGODB_URL: mongodb://mongo:27017/graphqlTodo

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - todo-app
    volumes:
      - mongo-data:/data/db
    command: mongod --quiet --logpath /dev/null
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://mongo:27017 --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 8081:8081
    networks:
      - todo-app
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

networks:
  todo-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
