services:
  - type: web
    name: client
    env: docker
    healthCheckPath: /health
    dockerfilePath: client/Dockerfile

  - type: web
    name: nginx
    env: docker
    healthCheckPath: /health
    dockerfilePath: nginx/Dockerfile
