services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 3050:80
    depends_on:
      - app

  client:
    image: santgt5/client-graphql-todo
    env:
      - WDS_SOCKET_PORT=0
