type Note {
    title: String!
    text: String!
    _id: ID
    done: Boolean
}

type Query {
    notes: [Note!]
}

type Mutation {
    addNewNote(title: String!, text: String!, done: Boolean): Note!
}
