type Note {
    title: String!
    text: String!
    _id: ID
    done: Boolean
}

type Query {
    getAllNotes: [Note]!
}

type Mutation {
    addNewNote(title: String!, text: String!, done: Boolean): Note!
    deleteNote(id: ID!): Note
}
