name: Deploy GraphQl-ToDo
on:
  push:
    branches: [main]

jobs:
  build:
    env:
      CI: true
    strategy:
      matrix:
        node-version: [18.14.2]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

        ########### Test ###########
      - name: Docker Compose Build
        run: docker compose -f "docker-compose.dev.yml" up -d

      - name: Wait for docker to finish building
        run: sleep 5

      - name: Check running containers
        run: docker ps -a

      - name: Unit Test client
        run: docker exec client npm run test

      - name: Unit Test server
        run: docker exec api npm run test

      - name: Check Eslint server
        run: docker exec api npm run test

      - name: Stop containers
        if: always()
        run: docker compose -f "docker-compose.dev.yml" down

        ########### Deploy ###########
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker Client images
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./client
          platforms: linux/arm64/v8
          push: true
          tags: santgt5/client-graphql-todo

      - name: Build and push Docker Server images
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./server
          platforms: linux/arm64/v8
          push: true
          tags: santgt5/server-graphql-todo

      - name: Build and push Nginx images
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./nginx
          platforms: linux/arm64/v8
          push: true
          tags: santgt5/nginx-graphql-todo
